name: Daily Ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ingest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git identity
        run: |
          git config --global user.name "eatingliam85"
          git config --global user.email "liam.gillies@gmail.com"

      - name: Commit to main
        run: |
          git diff --quiet || (git add . && git commit -m "Update latest UFC data" && git push origin main)

      - name: Commit to archive branch
        run: |
          git fetch origin || true
          if git ls-remote --exit-code --heads origin archive-data; then
            git checkout archive-data
          else
            git checkout --orphan archive-data
          fi
          mkdir -p archive
          cp -r archive/* . || true
          git add .
          git diff --cached --quiet || git commit -m "Archive UFC data"
          git push origin archive-data --force